// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
  tenant_id,
  actor_user_id,
  action,
  entity_type,
  entity_id,
  metadata,
  ip_address,
  user_agent
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  coalesce($6, '{}'::jsonb),
  $7,
  $8
)
RETURNING id, tenant_id, actor_user_id, action, entity_type, entity_id, metadata, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	TenantID    pgtype.UUID     `json:"tenant_id"`
	ActorUserID pgtype.UUID     `json:"actor_user_id"`
	Action      AuditActionEnum `json:"action"`
	EntityType  pgtype.Text     `json:"entity_type"`
	EntityID    pgtype.UUID     `json:"entity_id"`
	Metadata    interface{}     `json:"metadata"`
	IpAddress   *netip.Addr     `json:"ip_address"`
	UserAgent   pgtype.Text     `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TenantID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, actor_user_id, action, entity_type, entity_id, metadata, ip_address, user_agent, created_at
FROM audit_logs
WHERE tenant_id = $1
  AND ($2::audit_action_enum IS NULL OR action = $2)
  AND ($3::uuid IS NULL OR actor_user_id = $3)
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListAuditLogsParams struct {
	TenantID    pgtype.UUID         `json:"tenant_id"`
	Action      NullAuditActionEnum `json:"action"`
	ActorUserID pgtype.UUID         `json:"actor_user_id"`
	OffsetCount int32               `json:"offset_count"`
	LimitCount  int32               `json:"limit_count"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.TenantID,
		arg.Action,
		arg.ActorUserID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
