// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatusEnum string

const (
	AccountStatusEnumProspect AccountStatusEnum = "prospect"
	AccountStatusEnumActive   AccountStatusEnum = "active"
	AccountStatusEnumInactive AccountStatusEnum = "inactive"
)

func (e *AccountStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatusEnum(s)
	case string:
		*e = AccountStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatusEnum: %T", src)
	}
	return nil
}

type NullAccountStatusEnum struct {
	AccountStatusEnum AccountStatusEnum `json:"account_status_enum"`
	Valid             bool              `json:"valid"` // Valid is true if AccountStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatusEnum), nil
}

type ActivityTypeEnum string

const (
	ActivityTypeEnumMeeting ActivityTypeEnum = "meeting"
	ActivityTypeEnumCall    ActivityTypeEnum = "call"
	ActivityTypeEnumEmail   ActivityTypeEnum = "email"
	ActivityTypeEnumNote    ActivityTypeEnum = "note"
	ActivityTypeEnumTask    ActivityTypeEnum = "task"
)

func (e *ActivityTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityTypeEnum(s)
	case string:
		*e = ActivityTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityTypeEnum: %T", src)
	}
	return nil
}

type NullActivityTypeEnum struct {
	ActivityTypeEnum ActivityTypeEnum `json:"activity_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ActivityTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityTypeEnum), nil
}

type ApprovalStatusEnum string

const (
	ApprovalStatusEnumPending  ApprovalStatusEnum = "pending"
	ApprovalStatusEnumApproved ApprovalStatusEnum = "approved"
	ApprovalStatusEnumRejected ApprovalStatusEnum = "rejected"
)

func (e *ApprovalStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalStatusEnum(s)
	case string:
		*e = ApprovalStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalStatusEnum: %T", src)
	}
	return nil
}

type NullApprovalStatusEnum struct {
	ApprovalStatusEnum ApprovalStatusEnum `json:"approval_status_enum"`
	Valid              bool               `json:"valid"` // Valid is true if ApprovalStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalStatusEnum), nil
}

type AuditActionEnum string

const (
	AuditActionEnumCreate AuditActionEnum = "create"
	AuditActionEnumUpdate AuditActionEnum = "update"
	AuditActionEnumDelete AuditActionEnum = "delete"
	AuditActionEnumLogin  AuditActionEnum = "login"
)

func (e *AuditActionEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditActionEnum(s)
	case string:
		*e = AuditActionEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditActionEnum: %T", src)
	}
	return nil
}

type NullAuditActionEnum struct {
	AuditActionEnum AuditActionEnum `json:"audit_action_enum"`
	Valid           bool            `json:"valid"` // Valid is true if AuditActionEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditActionEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AuditActionEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditActionEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditActionEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditActionEnum), nil
}

type IntegrationProviderEnum string

const (
	IntegrationProviderEnumGoogle    IntegrationProviderEnum = "google"
	IntegrationProviderEnumMicrosoft IntegrationProviderEnum = "microsoft"
)

func (e *IntegrationProviderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntegrationProviderEnum(s)
	case string:
		*e = IntegrationProviderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for IntegrationProviderEnum: %T", src)
	}
	return nil
}

type NullIntegrationProviderEnum struct {
	IntegrationProviderEnum IntegrationProviderEnum `json:"integration_provider_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if IntegrationProviderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntegrationProviderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.IntegrationProviderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntegrationProviderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntegrationProviderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntegrationProviderEnum), nil
}

type IntegrationStatusEnum string

const (
	IntegrationStatusEnumActive  IntegrationStatusEnum = "active"
	IntegrationStatusEnumRevoked IntegrationStatusEnum = "revoked"
	IntegrationStatusEnumError   IntegrationStatusEnum = "error"
)

func (e *IntegrationStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntegrationStatusEnum(s)
	case string:
		*e = IntegrationStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for IntegrationStatusEnum: %T", src)
	}
	return nil
}

type NullIntegrationStatusEnum struct {
	IntegrationStatusEnum IntegrationStatusEnum `json:"integration_status_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if IntegrationStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntegrationStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.IntegrationStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntegrationStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntegrationStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntegrationStatusEnum), nil
}

type IntegrationTypeEnum string

const (
	IntegrationTypeEnumEmail    IntegrationTypeEnum = "email"
	IntegrationTypeEnumCalendar IntegrationTypeEnum = "calendar"
)

func (e *IntegrationTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntegrationTypeEnum(s)
	case string:
		*e = IntegrationTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for IntegrationTypeEnum: %T", src)
	}
	return nil
}

type NullIntegrationTypeEnum struct {
	IntegrationTypeEnum IntegrationTypeEnum `json:"integration_type_enum"`
	Valid               bool                `json:"valid"` // Valid is true if IntegrationTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntegrationTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.IntegrationTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntegrationTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntegrationTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntegrationTypeEnum), nil
}

type LossReasonEnum string

const (
	LossReasonEnumBudget     LossReasonEnum = "budget"
	LossReasonEnumCompetitor LossReasonEnum = "competitor"
	LossReasonEnumTiming     LossReasonEnum = "timing"
	LossReasonEnumNoDecision LossReasonEnum = "no_decision"
	LossReasonEnumOther      LossReasonEnum = "other"
)

func (e *LossReasonEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LossReasonEnum(s)
	case string:
		*e = LossReasonEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for LossReasonEnum: %T", src)
	}
	return nil
}

type NullLossReasonEnum struct {
	LossReasonEnum LossReasonEnum `json:"loss_reason_enum"`
	Valid          bool           `json:"valid"` // Valid is true if LossReasonEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLossReasonEnum) Scan(value interface{}) error {
	if value == nil {
		ns.LossReasonEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LossReasonEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLossReasonEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LossReasonEnum), nil
}

type OpportunityStageEnum string

const (
	OpportunityStageEnumNewLead     OpportunityStageEnum = "new_lead"
	OpportunityStageEnumQualified   OpportunityStageEnum = "qualified"
	OpportunityStageEnumProposal    OpportunityStageEnum = "proposal"
	OpportunityStageEnumNegotiation OpportunityStageEnum = "negotiation"
	OpportunityStageEnumClosedWon   OpportunityStageEnum = "closed_won"
	OpportunityStageEnumClosedLost  OpportunityStageEnum = "closed_lost"
)

func (e *OpportunityStageEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OpportunityStageEnum(s)
	case string:
		*e = OpportunityStageEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OpportunityStageEnum: %T", src)
	}
	return nil
}

type NullOpportunityStageEnum struct {
	OpportunityStageEnum OpportunityStageEnum `json:"opportunity_stage_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if OpportunityStageEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOpportunityStageEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OpportunityStageEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OpportunityStageEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOpportunityStageEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OpportunityStageEnum), nil
}

type OrderStatusEnum string

const (
	OrderStatusEnumPending   OrderStatusEnum = "pending"
	OrderStatusEnumConfirmed OrderStatusEnum = "confirmed"
	OrderStatusEnumCancelled OrderStatusEnum = "cancelled"
	OrderStatusEnumInvoiced  OrderStatusEnum = "invoiced"
)

func (e *OrderStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatusEnum(s)
	case string:
		*e = OrderStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatusEnum: %T", src)
	}
	return nil
}

type NullOrderStatusEnum struct {
	OrderStatusEnum OrderStatusEnum `json:"order_status_enum"`
	Valid           bool            `json:"valid"` // Valid is true if OrderStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatusEnum), nil
}

type QuoteStatusEnum string

const (
	QuoteStatusEnumDraft    QuoteStatusEnum = "draft"
	QuoteStatusEnumSent     QuoteStatusEnum = "sent"
	QuoteStatusEnumAccepted QuoteStatusEnum = "accepted"
	QuoteStatusEnumRejected QuoteStatusEnum = "rejected"
	QuoteStatusEnumExpired  QuoteStatusEnum = "expired"
)

func (e *QuoteStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuoteStatusEnum(s)
	case string:
		*e = QuoteStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for QuoteStatusEnum: %T", src)
	}
	return nil
}

type NullQuoteStatusEnum struct {
	QuoteStatusEnum QuoteStatusEnum `json:"quote_status_enum"`
	Valid           bool            `json:"valid"` // Valid is true if QuoteStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuoteStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.QuoteStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuoteStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuoteStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuoteStatusEnum), nil
}

type RoleEnum string

const (
	RoleEnumAdmin   RoleEnum = "admin"
	RoleEnumManager RoleEnum = "manager"
	RoleEnumSales   RoleEnum = "sales"
)

func (e *RoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleEnum(s)
	case string:
		*e = RoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleEnum: %T", src)
	}
	return nil
}

type NullRoleEnum struct {
	RoleEnum RoleEnum `json:"role_enum"`
	Valid    bool     `json:"valid"` // Valid is true if RoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleEnum), nil
}

type Account struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Name        string             `json:"name"`
	Industry    pgtype.Text        `json:"industry"`
	Website     pgtype.Text        `json:"website"`
	Phone       pgtype.Text        `json:"phone"`
	Status      AccountStatusEnum  `json:"status"`
	Memo        pgtype.Text        `json:"memo"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AccountLocation struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	Name         string             `json:"name"`
	Country      pgtype.Text        `json:"country"`
	PostalCode   pgtype.Text        `json:"postal_code"`
	Prefecture   pgtype.Text        `json:"prefecture"`
	City         pgtype.Text        `json:"city"`
	AddressLine1 pgtype.Text        `json:"address_line1"`
	AddressLine2 pgtype.Text        `json:"address_line2"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Activity struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	OpportunityID pgtype.UUID        `json:"opportunity_id"`
	ActivityType  ActivityTypeEnum   `json:"activity_type"`
	Subject       string             `json:"subject"`
	Detail        pgtype.Text        `json:"detail"`
	ActivityAt    pgtype.Timestamptz `json:"activity_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ApprovalRequest struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	RequestedBy    pgtype.UUID        `json:"requested_by"`
	ApproverUserID pgtype.UUID        `json:"approver_user_id"`
	Status         ApprovalStatusEnum `json:"status"`
	Reason         string             `json:"reason"`
	DecisionNote   pgtype.Text        `json:"decision_note"`
	DecidedAt      pgtype.Timestamptz `json:"decided_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      AuditActionEnum    `json:"action"`
	EntityType  pgtype.Text        `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Metadata    []byte             `json:"metadata"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Contact struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	LocationID  pgtype.UUID        `json:"location_id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	FullName    string             `json:"full_name"`
	Department  pgtype.Text        `json:"department"`
	Title       pgtype.Text        `json:"title"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	IsPrimary   bool               `json:"is_primary"`
	Memo        pgtype.Text        `json:"memo"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationConnection struct {
	ID                pgtype.UUID             `json:"id"`
	TenantID          pgtype.UUID             `json:"tenant_id"`
	UserID            pgtype.UUID             `json:"user_id"`
	Provider          IntegrationProviderEnum `json:"provider"`
	IntegrationType   IntegrationTypeEnum     `json:"integration_type"`
	ExternalAccountID string                  `json:"external_account_id"`
	Status            IntegrationStatusEnum   `json:"status"`
	AccessToken       pgtype.Text             `json:"access_token"`
	RefreshToken      pgtype.Text             `json:"refresh_token"`
	ExpiresAt         pgtype.Timestamptz      `json:"expires_at"`
	Scopes            []string                `json:"scopes"`
	CreatedAt         pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz      `json:"updated_at"`
}

type IntegrationEvent struct {
	ID                  int64                   `json:"id"`
	TenantID            pgtype.UUID             `json:"tenant_id"`
	Provider            IntegrationProviderEnum `json:"provider"`
	IntegrationType     IntegrationTypeEnum     `json:"integration_type"`
	ExternalEventID     pgtype.Text             `json:"external_event_id"`
	EventType           string                  `json:"event_type"`
	Payload             []byte                  `json:"payload"`
	LinkedAccountID     pgtype.UUID             `json:"linked_account_id"`
	LinkedContactID     pgtype.UUID             `json:"linked_contact_id"`
	LinkedOpportunityID pgtype.UUID             `json:"linked_opportunity_id"`
	OccurredAt          pgtype.Timestamptz      `json:"occurred_at"`
	CreatedAt           pgtype.Timestamptz      `json:"created_at"`
}

type KpiSnapshot struct {
	ID           int64              `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	SnapshotAt   pgtype.Timestamptz `json:"snapshot_at"`
	MetricKey    string             `json:"metric_key"`
	MetricValue  pgtype.Numeric     `json:"metric_value"`
	DimensionKey string             `json:"dimension_key"`
	Dimensions   []byte             `json:"dimensions"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      RoleEnum           `json:"role"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Opportunity struct {
	ID                pgtype.UUID          `json:"id"`
	TenantID          pgtype.UUID          `json:"tenant_id"`
	AccountID         pgtype.UUID          `json:"account_id"`
	ContactID         pgtype.UUID          `json:"contact_id"`
	OwnerUserID       pgtype.UUID          `json:"owner_user_id"`
	Name              string               `json:"name"`
	Stage             OpportunityStageEnum `json:"stage"`
	Probability       int16                `json:"probability"`
	Amount            pgtype.Numeric       `json:"amount"`
	ExpectedCloseDate pgtype.Date          `json:"expected_close_date"`
	ClosedAt          pgtype.Timestamptz   `json:"closed_at"`
	Memo              pgtype.Text          `json:"memo"`
	CreatedBy         pgtype.UUID          `json:"created_by"`
	CreatedAt         pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz   `json:"updated_at"`
	NextActionAt      pgtype.Timestamptz   `json:"next_action_at"`
	NextActionNote    pgtype.Text          `json:"next_action_note"`
}

type OpportunityLoss struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	OpportunityID pgtype.UUID        `json:"opportunity_id"`
	Reason        LossReasonEnum     `json:"reason"`
	Detail        pgtype.Text        `json:"detail"`
	LostAt        pgtype.Timestamptz `json:"lost_at"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	OpportunityID pgtype.UUID        `json:"opportunity_id"`
	OrderNo       string             `json:"order_no"`
	Amount        pgtype.Numeric     `json:"amount"`
	Status        OrderStatusEnum    `json:"status"`
	OrderedOn     pgtype.Date        `json:"ordered_on"`
	Note          pgtype.Text        `json:"note"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Quote struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	OpportunityID pgtype.UUID        `json:"opportunity_id"`
	QuoteNo       string             `json:"quote_no"`
	Amount        pgtype.Numeric     `json:"amount"`
	Status        QuoteStatusEnum    `json:"status"`
	IssuedOn      pgtype.Date        `json:"issued_on"`
	ValidUntil    pgtype.Date        `json:"valid_until"`
	Note          pgtype.Text        `json:"note"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
