// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CloseOpportunityAsLost(ctx context.Context, arg CloseOpportunityAsLostParams) error
	CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error)
	CountOpportunities(ctx context.Context, arg CountOpportunitiesParams) (int64, error)
	CountTenantUsers(ctx context.Context, arg CountTenantUsersParams) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateApprovalRequest(ctx context.Context, arg CreateApprovalRequestParams) (ApprovalRequest, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateIntegrationEvent(ctx context.Context, arg CreateIntegrationEventParams) (IntegrationEvent, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (AccountLocation, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error)
	CreateOpportunityLoss(ctx context.Context, arg CreateOpportunityLossParams) (OpportunityLoss, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error)
	DecideApprovalRequest(ctx context.Context, arg DecideApprovalRequestParams) (ApprovalRequest, error)
	ExportAccountsRows(ctx context.Context, tenantID pgtype.UUID) ([]ExportAccountsRowsRow, error)
	ExportOpportunitiesRows(ctx context.Context, tenantID pgtype.UUID) ([]ExportOpportunitiesRowsRow, error)
	GetForecastSummary(ctx context.Context, tenantID pgtype.UUID) ([]GetForecastSummaryRow, error)
	GetLatestKpiSnapshot(ctx context.Context, tenantID pgtype.UUID) ([]GetLatestKpiSnapshotRow, error)
	GetLossReasonAnalysis(ctx context.Context, tenantID pgtype.UUID) ([]GetLossReasonAnalysisRow, error)
	GetPipelineSummary(ctx context.Context, tenantID pgtype.UUID) ([]GetPipelineSummaryRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListActivitiesByOpportunity(ctx context.Context, arg ListActivitiesByOpportunityParams) ([]Activity, error)
	ListApprovalRequests(ctx context.Context, arg ListApprovalRequestsParams) ([]ApprovalRequest, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListContactsByAccount(ctx context.Context, arg ListContactsByAccountParams) ([]Contact, error)
	ListDealHealth(ctx context.Context, arg ListDealHealthParams) ([]ListDealHealthRow, error)
	ListDuplicateCandidates(ctx context.Context, tenantID pgtype.UUID) ([]ListDuplicateCandidatesRow, error)
	ListIntegrationConnections(ctx context.Context, tenantID pgtype.UUID) ([]IntegrationConnection, error)
	ListIntegrationEvents(ctx context.Context, arg ListIntegrationEventsParams) ([]IntegrationEvent, error)
	ListLocationsByAccount(ctx context.Context, arg ListLocationsByAccountParams) ([]AccountLocation, error)
	ListNextActions(ctx context.Context, arg ListNextActionsParams) ([]ListNextActionsRow, error)
	ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error)
	ListOrdersByOpportunity(ctx context.Context, arg ListOrdersByOpportunityParams) ([]Order, error)
	ListQuotesByOpportunity(ctx context.Context, arg ListQuotesByOpportunityParams) ([]Quote, error)
	ListTenantUsers(ctx context.Context, arg ListTenantUsersParams) ([]ListTenantUsersRow, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error)
	UpdateOpportunity(ctx context.Context, arg UpdateOpportunityParams) (Opportunity, error)
	UpdateOpportunityNextAction(ctx context.Context, arg UpdateOpportunityNextActionParams) (Opportunity, error)
	UpsertIntegrationConnection(ctx context.Context, arg UpsertIntegrationConnectionParams) (IntegrationConnection, error)
}

var _ Querier = (*Queries)(nil)
