// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenantUsers = `-- name: CountTenantUsers :one
SELECT count(*)::bigint
FROM memberships
WHERE tenant_id = $1
  AND ($2::role_enum IS NULL OR role = $2)
`

type CountTenantUsersParams struct {
	TenantID pgtype.UUID  `json:"tenant_id"`
	Role     NullRoleEnum `json:"role"`
}

func (q *Queries) CountTenantUsers(ctx context.Context, arg CountTenantUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantUsers, arg.TenantID, arg.Role)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
  tenant_id,
  user_id,
  role
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, tenant_id, user_id, role, is_active, created_at, updated_at
`

type CreateMembershipParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     RoleEnum    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.TenantID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT
  u.id,
  u.email,
  u.display_name,
  u.is_active,
  m.role,
  u.created_at,
  u.updated_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.tenant_id = $1
  AND ($2::role_enum IS NULL OR m.role = $2)
ORDER BY u.created_at DESC
LIMIT $4
OFFSET $3
`

type ListTenantUsersParams struct {
	TenantID    pgtype.UUID  `json:"tenant_id"`
	Role        NullRoleEnum `json:"role"`
	OffsetCount int32        `json:"offset_count"`
	LimitCount  int32        `json:"limit_count"`
}

type ListTenantUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	IsActive    bool               `json:"is_active"`
	Role        RoleEnum           `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTenantUsers(ctx context.Context, arg ListTenantUsersParams) ([]ListTenantUsersRow, error) {
	rows, err := q.db.Query(ctx, listTenantUsers,
		arg.TenantID,
		arg.Role,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantUsersRow{}
	for rows.Next() {
		var i ListTenantUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.IsActive,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships
SET role = $1, updated_at = now()
WHERE tenant_id = $2
  AND user_id = $3
RETURNING id, tenant_id, user_id, role, is_active, created_at, updated_at
`

type UpdateMembershipRoleParams struct {
	Role     RoleEnum    `json:"role"`
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.Role, arg.TenantID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
